@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3ODAyMTIwOCwiZXhwIjoxNzc4MDUwMDA4fQ.1rka211xUdwrRwFvgMYMRoCnmxTRtpnZyQoF_lAYiKY

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/active

###
GET http://localhost:3000/api/users/3

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "eduardo",
  "lastName": "Teste",
  "phone": "2499999-9999",
  "email": "p@p.com",
  "password": "david1234!"
}

###

DELETE http://localhost:3000/api/users/2

###

PATCH  http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "Hansen de Oliveira 22"
}

###
PATCH  http://localhost:3000/api/users/4/toggle

###
PATCH  http://localhost:3000/api/users/role/11
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "admin"
}