GET http://localhost:3000/api/users

###
POST  http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName":"larissa",
    "lastName":"polceno"
}

###
// Deletar
DELETE http://localhost:3000/api/users/3
###
// Atualizar
PATCH  http://localhost:3000/api/users/4
Content-Type: application/json

{
    "firstName": "Roseli",
    "lastName":"polceno"
}