GET http://localhost:3000/api/users  
// listar
###

POST  http://localhost:3000/api/users
Content-Type: application/json
// criar

{
    "firstName":"super 2",
    "lastName":"man",
    "email":"super@gmail.com",
    "phone": "(24) 99298-0960"
}

###

DELETE http://localhost:3000/api/users/6
// deletar
###


PATCH  http://localhost:3000/api/users/4
Content-Type: application/json
// atualizar

{
    "firstName": "Roseli",
    "lastName":"Polceno"
}
###
GET http://localhost:3000/api/users/5
// listar por id

###
PATCH  http://localhost:3000/api/users/8/toggle
Content-Type: application/json
// delete-soft desativar

{
    "isActive":false
}

###
GET http://localhost:3000/api/users/active
// listar os ativos